# This section declares settings for the server.
[server]
host = "0.0.0.0"                # server host
port = 8080                     # server port
default_n = 10                  # defulat number of items on paging

# This section declares setting for the database.
[database]
path = "redis://127.0.0.1:6398" # database path

# This section declares hyperparameters for the recommendation model.
[leader]

[leader.params]
lr = 0.05                       # learning rate
reg = 0.01                      # regularization strength
n_epochs = 100                  # number of epochs
n_factors = 10                  # number of factors
random_state = 21               # random state (seed)
use_bias = false                # use bias
init_mean = 0.0                 # mean of gaussian initial parameter
init_std = 0.001                # standard deviation of gaussian initial parameter
weight = 1.0                    # alpha value, depend on context
