language: go

go:
 -  master

before_install:
  - go get -v ./...

install: true

script:
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
